version: '3.1'
services:

  mysql_db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass123word
    networks:
      - back-end

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9001:80
    environment:
      PMA_ARBITRARY: 1
      PMA_PORT: 3306
      PMA_HOST: mysql_db
      PMA_USER: root
      PMA_PASSWORD: pass123word
    depends_on:
      - mysql_db
    networks:
      - front-end
      - back-end

  flask-api:
    build: ./flask-api
    volumes:
      - log_data:/opt/source-code/log
      - ./flask-api/:/opt/source-code
    restart: always
    ports:
      - 5000:5000
    networks:
      - front-end
      - back-end

networks:
  front-end:
  back-end:  
volumes:
  db_data:
  log_data: