version: '3.1'
services:

  mysql_db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass123word
    networks:
      - back-end

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9001:80
    environment:
      PMA_ARBITRARY: 1
      PMA_PORT: 3306
      PMA_HOST: mysql_db
      PMA_USER: root
      PMA_PASSWORD: pass123word
      UPLOAD_LIMIT: 100000000
    depends_on:
      - mysql_db
    networks:
      - front-end
      - back-end

  flask-api:
    build: ./flask-api
    volumes:
      - api_log:/opt/source-code/log
      - ${PWD}/flask-api/app.py:/opt/source-code/app.py
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - mysql_db
    networks:
      - front-end
      - back-end

  pw_snapshot:
    build: ./pw_snapshot
    volumes:
      - pw_log:/home/pwuser/log
      - ${PWD}/pw_snapshot/app.py:/home/pwuser/app.py
      - ${PWD}/pw_snapshot/note.sh:/home/pwuser/note.sh
      - ${PWD}/pw_snapshot/pics:/home/pwuser/pics
    restart: always
    ports:
      - 8888:8888
    depends_on:
      - mysql_db
    networks:
      - back-end

networks:
  front-end:
  back-end:  
volumes:
  api_log:
  pw_log:
  db_data:
