version: '3.1'
services:

  mysql-db:
    image: mysql:latest
    volumes:
      - db-data:/var/lib/mysql
      - ${PWD}/bkup:/bkup
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass123word
    networks:
      - back-end

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9001:80
    environment:
      PMA_ARBITRARY: 1
      PMA_PORT: 3306
      PMA_HOST: mysql-db
      PMA_USER: root
      PMA_PASSWORD: pass123word
      UPLOAD_LIMIT: 100000000
    depends_on:
      - mysql-db
    networks:
      - front-end
      - back-end

  flask-api:
    build: ./flask-api
    volumes:
      - api-log:/opt/source-code/log
      - ${PWD}/flask-api/app.py:/opt/source-code/app.py
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - mysql-db
    networks:
      - front-end
      - back-end

  pw-snapshot:
    container_name: pw-snapshot
    build: ./pw_snapshot
    volumes:
      - pw-log:/home/pwuser/log
      - ${PWD}/pw_snapshot/app.py:/home/pwuser/app.py
      - ${PWD}/pw_snapshot/note.sh:/home/pwuser/note.sh
      - ${PWD}/pw_snapshot/pics:/home/pwuser/pics
      - ${PWD}/pw_snapshot/cache:/home/pwuser/cache
    restart: always
    ports:
      - 8888:8888
    depends_on:
      - mysql-db
    networks:
      - back-end

  apache-ui:
    image: php:8.0-apache
    volumes:
      - ${PWD}/web-ui:/var/www/html
      - ${PWD}/./pw_snapshot/pics/pfp:/var/www/html/assets/img/pfp
    ports:
      - 80:80
    depends_on:
      - flask-api
    networks:
      - front-end
      - back-end  

  # sandbox:
  #   build: ./sandbox
  #   volumes:
  #     - ${PWD}/sandbox:/home/pwuser
  #   restart: always
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - mysql_db
  #   networks:
  #     - front-end
  #     - back-end

networks:
  front-end:
  back-end:  
volumes:
  api-log:
  pw-log:
  db-data:
